### ISSUE TITLE
Custom methods don't resolve properly with path parameters

### ISSUE THREAD

**Issue by briangweber** [cdimascio/express-openapi-validator#1022]
**Describe the bug**
The route sorting puts `/v1/resources/:id` before `/v1/resources/:id\\:clone`, so the route with the custom action will not be chosen.

**To Reproduce**
Add two endpoints:
* GET /v1/resources/{id}
* PUT /v1/resources/{id}:clone

Call with PUT /v1/resources/1234:clone

**Actual behavior** 
If you call with PUT /v1/resources/1234:clone, the validator returns "PUT method not allowed"

**Expected behavior**
Routes with custom methods should be considered before the same route without custom methods.

**Examples and context**
I confirmed that path-to-regexp will match either with `/v1/resources/1234:clone`, so sort order of evaluation is important.

```
/v1/resources/{id}:
  get:
    parameters:
      - name: id
        in: path
        type: string
/v1/resources/{id}:clone:
  put:
    parameters:
      - name: id
        in: path
        type: string
```
