### ISSUE TITLE
Query parameters including `[]` are not parsed correctly.

### ISSUE THREAD

**Issue by ckeboss** [cdimascio/express-openapi-validator#136]
If you have a parameter such as:
```
    FilterParam:
      name: filter[foo]
      in: query
      description: Filter foo
      required: false
      style: form
      explode: false
      schema:
        type: array
        items:
          type: string
```
which `?filter[foo]=1` would be valid, the validator responds with `Unknown query parameter filter` because it uses whichever query parser express is configured with. In this example, `req.query` would be:
```
{
  filter: {
    foo: 1
  }
}
```
which fails validation. I would propose to not use the express parsed query param and instead parse it independently to handle this.
