### ISSUE TITLE
Support readOnly + required combination

### ISSUE THREAD

**Issue by Haruki-Mortis** [cdimascio/express-openapi-validator#145]
Hello there.

There is a problem if a property is required and readOnly at the same time.

In follow case the schema works fine in the response validation.
However, the request validation fails if no id is passed.

**Current validation result**
```
    response:
        id*
        username*
        name
    request:
        id*
        username*
        name
```

**Expected validation result**
```
    response:
        id*
        username*
        name
    request:
        username*
        name
```

**Schema**
```
  UserListViewDefault:
      description: default
      type: object
      required:
        - id
        - username
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        username:
           type: string
        name:
           type: string
```
**[Documentation ](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#fixed-fields-20)definition**
**readOnly**
Relevant only for Schema "properties" definitions. Declares the property as "read only". This means that it MAY be sent as part of a response but SHOULD NOT be sent as part of the request. If the property is marked as readOnly being true and is in the required list, the required will take effect on the response only. A property MUST NOT be marked as both readOnly and writeOnly being true. Default value is false.

**writeOnly** (The writeOnly functionality has not been checked yet)
Relevant only for Schema "properties" definitions. Declares the property as "write only". Therefore, it MAY be sent as part of a request but SHOULD NOT be sent as part of the response. If the property is marked as writeOnly being true and is in the required list, the required will take effect on the request only. A property MUST NOT be marked as both readOnly and writeOnly being true. Default value is false.
