### ISSUE TITLE
allowEmptyValue flag is ignored

### ISSUE THREAD

**Issue by AlekseyMko** [cdimascio/express-openapi-validator#190]
Hello, looks like ``allowEmptyValue`` flag is not validated

**yuml snippet:**
```
paths:
  /storyInfo:
    get:
      tags:
        - userId
      summary: Detailed information about story
      operationId: storyInfo
      parameters:
        - name: storyId
          in: query
          required: true
          schema:
            type: string
          allowEmptyValue: false
```

**request url:**
``/api/storyInfo?storyId`` or ``/api/storyInfo?storyId=``

**AR**: Validator accepted the query, the handler was called
**ER** Validator should throw an error
