### ISSUE TITLE
No validation for custom headers

### ISSUE THREAD

**Issue by doron-au10tix** [cdimascio/express-openapi-validator#232]
Hi,

I have defined in my open api spec required headers for an endpoint and although not received, the validator doesn't reject the request and performs no validation.

example of the open-api spec:
```
 get:
      responses:
        '200':
          description: A JSON array of objects
      parameters:
        - name: x-userId
          in: header
          schema:
            type: string
            maxLength: 255
          required: true
```

**Comment by cdimascio** [comment]
@doron-au10tix i wrote a couple test cases for this. they all work properly
see the 3 cases [here](https://github.com/cdimascio/express-openapi-validator/blob/master/test/headers.2.spec.ts#L46)

**Comment by cdimascio** [comment]
are you using the latest version or at least latest stable `v3.6.7`

**Comment by cdimascio** [comment]
FYI: [this](https://github.com/cdimascio/express-openapi-validator/blob/master/test/resources/headers.yaml) is the spec i used for testing

**Comment by stanleynguyen** [comment]
I'm having the same error for v3.7.0 as well. My spec has something like this:
```
get
  parameters:
    clientVersion:
      - in: header
         name: client-version
         description: The requester's client version used to access this service
         schema:
           type: string
           example: 'v1.0.0'
         required: true
```
