### ISSUE TITLE
Single item in array type query parameter is not converted to array

### ISSUE THREAD

**Issue by DylanBowden** [cdimascio/express-openapi-validator#27]
Hi, I have the following query parameter

```
- in: query
  name: publication_time
  required: true
  style: form
  explode: true
    schema:
      type: array
      minItems: 1
      items:
        type: string
```

When I pass muliple values like `?publication_time=someDay&publication_time=otherDay` it's fine but when I pass a single value `?publication_time=someDay`, I get the error

```
{ errors:
   [ { path: '.query.publication_time',
       message: 'should be array',
       errorCode: 'type.openapi.validation' } ] }
```

Am I doing something wrong? Is there another way to pass an array with a single parameter using `style=form` and `explode=true` ?

Thanks

**Comment by DylanBowden** [comment]
Update: I found a way around this

```
- in: query
  name: publication_time
  required: true
  schema:
    oneOf:
      - type: string
        format: date-time
      - type: array
        minItems: 1
        items:
          type: string
```

My single value isn't in array-form but at least it's no-longer blocking
