### ISSUE TITLE
Default values missing in query

### ISSUE THREAD

**Issue by xeoneux** [cdimascio/express-openapi-validator#287]
First of all, thanks a lot for this package @cdimascio 

I couldn't find any other lib that handles OpenAPI v3 well, is well maintained and has a good amount of tests 😄 

So here's my issue:
For example, I'm using this schema:
```yaml
Sort:
      properties:
        field:
          default: id
          enum:
            - id
          type: string
        order:
          default: ASC
          enum:
            - ASC
            - DESC
          type: string
      type: object
```

Along with this query item:
```yaml
parameters:
        - in: query
          name: sort
          required: false
          schema:
            $ref: '#/components/schemas/Sort'
          style: deepObject
```

Then, inside the route, the `req.query.sort` is an empty object instead of the default values, `{ sort: {field: 'id', order: 'ASC'} }`

Is the not the desired behaviour or is it because of the `deepObject` style?
