### ISSUE TITLE
NPE when using object query parameters with style: form and explode: true

### ISSUE THREAD

**Issue by rhalukongor** [cdimascio/express-openapi-validator#294]
**Describe the bug**
When a schema includes object query parameters with style: form and explode:true an NPE is thrown:

**To Reproduce**
Try using the first schema in this [SO answer](https://stackoverflow.com/a/49199240)

**Actual behavior** 
An NPE is thrown with the following stacktrace:
```
TypeError: Cannot set property '<field name>' of undefined
 at .../node_modules/express-openapi-validator/dist/middlewares/parsers/req.parameter.mutator.js:181:52
 at Array.forEach ()
 at RequestParameterMutator.explodedJsonObjectAndMutateRequest (.../node_modules/express-openapi-validator/dist/middlewares/parsers/req.parameter.mutator.js:174:28)
 at RequestParameterMutator.handleFormExplode (.../node_modules/express-openapi-validator/dist/middlewares/parsers/req.parameter.mutator.js:111:14)
 at .../node_modules/express-openapi-validator/dist/middlewares/parsers/req.parameter.mutator.js:55:26
 at Array.forEach ()
 at RequestParameterMutator.modifyRequest (.../node_modules/express-openapi-validator/dist/middlewares/parsers/req.parameter.mutator.js:39:20)
 at Object.GET-/api/article-views-not_provided (.../node_modules/express-openapi-validator/dist/middlewares/openapi.request.validator.js:72:21)
 at RequestValidator.validate (.../node_modules/express-openapi-validator/dist/middlewares/openapi.request.validator.js:45:41)
 at requestValidationHandler (.../node_modules/express-openapi-validator/dist/index.js:135:79)
```

**Expected behavior**
Validation should work

**Examples and context**
This is the schema I've had the error:
```
  parameters:
    parent:
      name: parent
      in: query
      required: true
      schema:
        type: object
        properties:
          child1:
            type: string
          child2:
            type: array
            items:
              type: string
        additionalProperties: false
        minProperties: 1
      style: form
      explode: true
```

**Comment by cdimascio** [comment]
@rhalukongor the spec looks malformatted

note: I often use https://editor.swagger.io/ when writing the spec to ensure its syntactically correct.

try something like this:
```yaml
paths:
  /node:
    get:
      operationId: "getNode"
      parameters:
        - name: parent
          in: query
          style: form
          schema:
            type: object
            properties:
              child1:
                type: string
              child2:
                type: array
                items:
                  type: string
            additionalProperties: false
            minProperties: 1
```
