### ISSUE TITLE
Unintelligable error when requesting POST method

### ISSUE THREAD

**Issue by nrail-joerg-walter** [cdimascio/express-openapi-validator#297]
I get in the debugger:

```
MissingRefError {message: "can't resolve reference #/components/schemas/NewPa…", missingRef: "#/components/schemas/NewPasskey/properties/newPass…", missingSchema: ""}

"can't resolve reference #/components/schemas/NewPasskey/properties/newPasskey from id #"
"#/components/schemas/NewPasskey/properties/newPasskey"
```

The schema NewPasskey does exist. The prop newPasskey does exist in that schema.
The ref #/components/schemas/NewPasskey does exist. But it is not involved in the requested route/method.

NewPasskey contains a ref to another file. When I remove that ref the request passes.
But then a similar error is displayed on response validation.

Finally after removing all refs to two schemas in a separate file it passed completely.

I had to do that for NewPasskey and another schema in common.yaml

I have:

```
    NewPasskey:
      type: object
      additionalProperties: false
      properties:
        newPasskey:
          #type: string
          description: 
          $ref: 'common.yaml#/components/schemas/Passkey'
      required:
        - newPasskey
```

and in common.yaml

```
components:

  schemas:

    Passkey:
      type: string
      maxLength: 2000
      example: 'ssssssssht.*;'
```
But these schemas are not the only schemas referenced in that other file.

The referenced schemas are both such simple strings.

When I move the offending schemas from common.yaml to the main file it works.
