### ISSUE TITLE
Add support for JSONSchema readOnly keyword

### ISSUE THREAD

**Issue by cdimascio** [cdimascio/express-openapi-validator#34]
Support readonly keyword 
https://json-schema.org/latest/json-schema-validation.html#rfc.section.10.3
Note: Ajv supports readOnly

**Comment by cdimascio** [comment]
reposting the following info provided by @gonenduk

For example, when I create a new product - I supply several fields and the product is created in the db and an id is given to it, as well as ownerId and creation time. The newly created object is returned with the new values - all of them.
Later on I can use this id to retrieve the product, delete it or update it. But I can never change the id or supply it when creating a new product (nor the creation time or the ownerId).
Read-only fields supplied on post or put or patch should not pass validation.
```
components:
  schemas:
    Product:
      type: object
      properties:
        _id:
          type: string
          readOnly: true
        title:
          type: string
        price:
          type: number
        ownerId:
          type: string
          readOnly: true
        createdAt:
          type: string
          format: date-time
          readOnly: true
        updatedAt:
          type: string
          format: date-time
          readOnly: true
```
The read-only fields are returned on get (and maybe delete if you returned the deleted object), but cannot be given on post, put and patch!
