### ISSUE TITLE
Why do we validate the server variables? There is no such limitation in OpenAPI 3 specification

### ISSUE THREAD

**Issue by xg1990** [cdimascio/express-openapi-validator#380]
## Problem description

if we have a openapi 3.0 specification like this:

```yaml
servers:
  - url: https://api.example.com/{basePath}
    description: Production server (uses live data)
    variables:
        basePath:
            default: "v1/path-a/path-b/pathC

```

It will report error that the `basePath` doesn't match the pattern "[^\/#\?]+?"

## Discussion

This pattern check comes from the package `path-to-regexp`.

But I don't think we need such constrains. There is no such limitation in OpenAPI 3 specification

According to https://swagger.io/docs/specification/api-host-and-base-path/, it says:

> Variables can have arbitrary values, or may be restricted to an enum. 

<img width="742" alt="image" src="https://user-images.githubusercontent.com/1443518/94640620-8f20e080-0322-11eb-81ab-fecce1e5a674.png">
