### ISSUE TITLE
Response property casting

### ISSUE THREAD

**Issue by Haruki-Mortis** [cdimascio/express-openapi-validator#396]
Hey, I updated from version 3.16.11 to the latest version 4.2.0.
Before the update, the values in the response json were automatically casted to the defined property type.

```typescript
// origin object
{
    createdAt: '1602582518'
}

//object after response.json()
{
    createdAt: 1602582518
}
```

In the openapi spec:
```yml
properties:
    createdAt:
        type: number
        format: int64
        nullable: true
```

This behavior is lost in the latest version.
Is there an option to enable this property casting?
