### ISSUE TITLE
Confuse why is not working (probably my fault)

### ISSUE THREAD

**Issue by bmaschio** [cdimascio/express-openapi-validator#592]
**Describe the bug**
The validation seems to not be triggered 

**To Reproduce**
try to call my endpoint

curl --request POST \
  --url http://localhost/api/informations \
  --header 'Content-Type: application/json' \
  --data '{
	"source" : "some_device",
	"value" : 1.453543543534
}'

**Actual behavior** 
Returns 200 I was expecting some error

**Expected behavior**
I was expecting some error

**See file**
[openapi-validator.zip](https://github.com/cdimascio/express-openapi-validator/files/6409902/openapi-validator.zip)

**Comment by cdimascio** [comment]
hello @bmaschio the schema for this POST request is defined as follows:
```
    informationSingle:
      type: object
      properties:
        source:
          type: string
        sourceTime:
          type: number
        value:
          type: number
```

note that all fields are optional. also the values you provided are compatible with the defined types, thus the request is valid and should pass validation.  all in all, the behavior is correct. 

what were you expecting?

(closing this out, feel free to post questions if you still have them)
