### ISSUE TITLE
Array query params cannot be parsed req.query in Express 5

### ISSUE THREAD

**Issue by jeremydrichardson** [cdimascio/express-openapi-validator#599]
**Describe the bug**
When defining an array query parameter in OpenAPI, express-openapi-validator will fail to validate.

**To Reproduce**
Use the following query parameter
```
- name: ids
      in: query
      schema:
        type: array
        items:
          type: string
      style: form
      explode: false
      allowReserved: true
```
with the following query string in url
```
?ids=12345,23456
```
using Express 5

**Actual behavior** 
Validation will fail with the error "Bad Request: request.query.ids should be array"

**Expected behavior**
The query parameter should be coerced into an array and validated.

**Examples and context**
The error is evident in the function `parseJsonArrayAndMutateRequest`. If you console log the value of `value` and `req[field][name]` after is has been assigned value, nothing change. 

From reading further it appears that there is a breaking change in Express 5 where the req object is no longer modifiable in the way it was before. It is unclear the correct way to modify the req object in Express 5.

Reference
req.query is now a getter - https://github.com/expressjs/express/commit/dcc4eaabe86a4309437db2a853c5ef788a854699
