### ISSUE TITLE
using enum in schema leads to unexpected results

### ISSUE THREAD

**Issue by dod38fr** [cdimascio/express-openapi-validator#60]
Hi

With the following schema:
```
    EnumBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              enum:
                - foo
              required:
                - foo
              properties:
                foo:
                  type: string
```

A call with body set to `{foo: 'bar', bogus: 'baz'}` is rejected (which is expected), but a call with body set to `{foo: 'bar'}` is also rejected which is not expected.

Is this a bug or did I misunderstood OpenApi specification ?

If needed I can provide a patch so that express-openapi-validator's tests show this behavior.

All the best

**Comment by cdimascio** [comment]
i'm a bit confused by what you are trying to express. 
```
    EnumBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              enum:   #<--- You object that is an enum with a string value. i dont think this makes sense
                - foo
              required:  # <-- here you are saying you want the foo property below to be required. that's good
                - foo
              properties:
                foo:
                  type: string

```
  
Perhaps you want something like
```
        content:
          application/json:
            schema:
              type: object
              required:
                - foo
              properties:
                foo:
                  type: string      
                  enum:
                    - bar
                    - baz
```
