### ISSUE TITLE
path params are not coerced when declared under the path

### ISSUE THREAD

**Issue by jazzzz** [cdimascio/express-openapi-validator#612]
**Describe the bug**

Path params are coerced when declared under a method, but not when declared under the path for all the methods.

**To Reproduce**

With the following `openapi.yaml`, `req.params.id` is a string, whereas it should be a number:

```yaml
paths:
    /my-path/{id}:
        parameters:
        -   name: id
            in: path
            schema:
                type: number
        post:
```

With the following `openapi.yaml`, `req.params.id` is a number:

```yaml
paths:
    /my-path/{id}:
        post:
            parameters:
            -   name: id
                in: path
                schema:
                    type: number
````

**Actual behavior** 

The path parameters are not coerced (`req.params.id` is a string).

**Expected behavior**

The path parameters are coerced (`req.params.id` is a number).

**Examples and context**

See the example above.
