### ISSUE TITLE
Path parameters are not coerced

### ISSUE THREAD

**Issue by vomc** [cdimascio/express-openapi-validator#672]
It seems that though the docs state otherwise that path parameters are not coerced. I am using version `4.12.14`

For example I have a simple endpoint, specified like this

```yaml
/v1/foo/{deviceId}:
    parameters:
      - name: deviceId
        in: path
        description: id of the device
        required: true
        schema:
          type: integer
    get:
      description: get some device
      x-eov-operation-handler: some_controller
      operationId: getDevice
```

Then in my controller, if I log out the incoming param like this

```js
// Request, Response, NextFunction are just the default Express types
export const getDevice = (req: Request, res: Response, next: NextFunction) => {
	console.log(JSON.stringify(req.params))
```
I see
```js
[Node] {"deviceId":"999"}
```

I am not sure if I am misunderstanding the docs but my assumption would be that since I specified the `deviceId` path param as `type: integer` and since path params are supposedly coerced by default, I would have expected this to come in as an int in my controller.

Is this not correct?
