### ISSUE TITLE
Option removeAdditional with allOf

### ISSUE THREAD

**Issue by YaakovR** [cdimascio/express-openapi-validator#696]
I refrained from labeling this a Bug report or Feature request, since it may be my own syntactic error 😄.

**OpenApiValidator config:**
```
app.use(OpenApiValidator.middleware({
  apiSpec: openapiSpec,
  validateRequests: false,
  validateResponses: {
    removeAdditional: 'all',
    coerceTypes: true,
  },
  validateApiSpec: true,
  validateSecurity: false,
}));
```

**OpenAPI path:**
```
get:
  responses:
    '200':
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  allOf:
                  - "$ref": "#/components/schemas/User"
                  - type: object
                    properties:
                      user_group:
                        "$ref": "#/components/schemas/UserGroup"
```

**OpenAPI schema**
```
User:
  type: object
  properties:
    id:
      type: integer
      readOnly: true
    name:
      type: string

UserGroup:
  type: object
  properties:
    id:
      type: integer
      readOnly: true
    name:
      type: string
```

**Expected JSON return data**
```
{
  "data": [
    {
        "id": 6,
        "name": "Abraham",
        "user_group": {
          "id": 2,
          "name": "Castle"
        }
    },
    {
        "id": 4,
        "name": "Isaac",
        "user_group": {
          "id": 2,
          "name": "Castle"
        }
    }
  ]
}
```

**Actual JSON return data**
```
{
    "data": [
        {},
        {}
    ]
}
```

I'm wondering why  `removeAdditional: 'all'` empties the entire objects. Everything works fine when removing the `removeAdditional: 'all'`.
In addition, all is good when writing out the schema instead of referencing. Does `express-openapi-validator` not support `allOf`?

The schema seems to be valid since the `validateApiSpec: true` passes.
Also, I'm using `swagger-ui-express`, and it is giving no issues interpreting the schemas inside of the `allOf`.

I'd appreciate if someone can look at this and advise if there is something I should be doing differently or if this is an issue with  `swagger-ui-express`.

Thank you very much!!
