### ISSUE TITLE
Support for unicode in pattern 

### ISSUE THREAD

**Issue by minut-shan** [cdimascio/express-openapi-validator#701]
**Is your feature request related to a problem? Please describe.**
Suppor unicode in pattern as på JSON schema 2020-12, like the following: 
```
      schema:
        type: string
        example: "North Street"
        pattern: ^[\p{L}\p{N}*-]+$
```
The problem is that currenly the version of `ajv` being used is 6.12.6, which does not pass the `u` flag in the Regexp constructor. As stated in their changelog https://github.com/ajv-validator/ajv/releases/tag/v7.0.0 

**Describe the solution you'd like**
Bump `ajv` to version 7.0.0
