### ISSUE TITLE
Optional deepObject query params with no defaults are incorrectly added to req.query

### ISSUE THREAD

**Issue by sinclairs** [cdimascio/express-openapi-validator#734]
**Describe the bug**
Given an optional deepObject query parameter that has no default value. If the parameter is omitted from the request, it is incorrectly added to `req.query` with an empty object as its value.

This also causes validation to incorrectly kick-in for the inserted property, which explains the behaviour outlined in [this related issue](https://github.com/cdimascio/express-openapi-validator/issues/656).

**To Reproduce**

Given this parameter definition:
```yaml
name: sort
example:
  field: created
  order: desc
in: query
style: deepObject
required: false
schema:
  type: object
  required:
    - field
    - order
  properties:
    field:
      enum:
        - created
    order:
      enum:
        - desc
        - asc
```

Make a request and omit the `sort` parameter

**Actual behavior** 
`req.query` has the `sort` parameter added to it:
```JavaScript
{
    sort: {}
}
``` 

**Expected behavior**
`req.query` should **_not_** have the `sort` parameter added to it:
```JavaScript
{}
```
