### ISSUE TITLE
Support for OpenAPI 3.1.0

### ISSUE THREAD

**Issue by harryc9** [cdimascio/express-openapi-validator#755]
Hi, are there plans to support OpenAPI 3.1.0 with this library?

We're currently running into issues when validating the API spec because Stoplight API exports are using features exclusive to 3.1.0. Mainly trying to avoid workarounds where we manually downgrade the OA version and remove the said block post-export.

The specific feature being a change to the `Schema` [definition](https://spec.openapis.org/oas/v3.1.0#fixed-fields-19) to contain `examples`

```
components:
  schemas:
    User:
      title: User
      type: object
      description: ''
      examples:
        - id: 0
          firstName: Bob
          lastName: Ross
          email: bob@example.com
          emailVerified: true
          createTime: '2019-08-24T12:42:12Z'
          lastUpdateTime: '2020-09-23T08:17:41Z'
``` 

Thank you!
