### ISSUE TITLE
format: date accepts incorrect month range

### ISSUE THREAD

**Issue by mcoevert** [cdimascio/express-openapi-validator#858]
**Describe the bug**
When describing a query parameter with a date schema, it incorrectly accepts dates with the month 13 to 19:
`2021-13-01`
`2021-14-01`
etc..

From the 20th month, it correctly responded with a 400
`2021-20-01`

**To Reproduce**

```
/my-endpoint:
    get:
      parameters:
        - name: from
          in: query
          required: true
          schema:
            type: string
            format: "date"
```

Then request the endpoint with the example dates.

**Actual behavior** 
`2021-13-01` is being validated as a correct date

**Expected behavior**
`2021-13-01` should throw a 400, describing an incorrect date
