### ISSUE TITLE
Multiple path params break support for URI path param

### ISSUE THREAD

**Issue by Mitchell3514** [cdimascio/express-openapi-validator#887]
**Describe the bug**
As per the [FAQ](https://github.com/cdimascio/express-openapi-validator/wiki/Documentation#faq), we should be able to define paths that end on a path parameter acting as a wildcard/use URI format.  
However, when we introduce a second path parameter, the middleware always throws an error and the server returns status code `500`.

**To Reproduce**
1. Create the validation middleware using an OpenAPI specification that includes a path with multiple path parameters of which the last (at the end) is a wildcard as per `RFC-6570`. For example:
    ```yaml
    /namespaces/{id}/files/{path}*:
      get:
        parameters:
          - name: path
            in: path
            required: true
            schema:
              type: string
    ```
2. Create an Express application with the middleware and call any (existing or non-existing) route.

**Actual behavior** 
The middleware always responds with `500 - Internal Server Error`

**Expected behavior**
The middleware validates the internal path parameter as per usual and parses the wildcard parameter at the end.

**Examples and context**
Original use-case: #457 implemented in #491 
I have added a commit to my fork that includes tests which reproduce this issue: https://github.com/Mitchell3514/express-openapi-validator/commit/0c5531869055500140dcbb6aee5da98b9c643b2a
