### ISSUE TITLE
Schema is marked as invalid, using `oneOf` inside `allOf`

### ISSUE THREAD

**Issue by jmechevarria** [cdimascio/express-openapi-validator#902]
**Describe the bug**
I try to use `oneOf` inside `allOf` in my schema, but validator says request body is invalid

**To Reproduce**

This is the schema:

      RequestDTO:
        type: object
        additionalProperties: false
        allOf:
          - oneOf:
              - type: object
                additionalProperties: false
                properties:
                  prop1:
                    type: string
              - type: object
                additionalProperties: false
                properties:
                  prop2:
                    type: string
                    enum: [this, that]
                    default: this
          - type: object
            additionalProperties: false
            properties:
              prop3:
                type: string

**Actual behavior** 
When submitting the following request body:

    { "prop1": "a value", "prop3": "another value" }

Error: 
`
request/body must NOT have additional properties, request/body must NOT have additional properties, request/body must NOT have additional properties, request/body must match exactly one schema in oneOf, request/body must NOT have additional properties, request/body must NOT have additional properties, request/body must NOT have additional properties
`

**Expected behavior**
I would expect that request to be validated OK by that schema.

**Additional information**

The intent here is to have a schema that allows sending either `prop1` and `prop3` or `prop2` and `prop3`

This is what I see in the OpenAPI SwaggerUI preview window (in VSCode), which looks OK:

![Screenshot 2024-02-06 at 9 45 32 p m](https://github.com/cdimascio/express-openapi-validator/assets/31573181/cd8f43f6-0b4e-4508-a386-eae03b49462e)

Also, I'm using [openapi-typescript-codegen](https://github.com/ferdikoomen/openapi-typescript-codegen) to generate my TS clients and that also looks OK:

```
/* generated using openapi-typescript-codegen -- do no edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

export type RequestDTO = (
  | {
      prop1?: string;
    }
  | {
      prop2?: RequestDTO.prop2;
    }
) & {
  prop3?: string;
};

export namespace RequestDTO {
  export enum prop2 {
    THIS = "this",
    THAT = "that",
  }
}
```

Am I assuming something wrong about how my schema should behave with this input?

**Comment by jmechevarria** [comment]
Two years later, issue persists.

It also looks like this approach is restricted in both ways, ie: I get an error if I send the "additional" property, and I get an error if I don't 😃 .

It all revolves around `additionalProperties: false` and where it is placed, getting slightly different errors depending on if it is placed at the root level of the schema, or inside `allOf`, or inside one of the items of `oneOf`.

For example, with this configuration:

```
    RequestDTO:
      type: object
      additionalProperties: false
      allOf:
        - oneOf:
            - type: object
              properties:
                prop1:
                  type: string
                prop2:
                  type: string
              required: [prop1]
            - type: object
              properties:
                prop3:
                  type: string
                  enum: [this, that]
                  default: this
                prop4:
                  type: string
              required: [prop4]
        - type: object
          properties:
            prop5:
              type: string
```

If I send: `{
  "prop1": "string",
  "prop2": "string",
  "prop5": "string"
}`

I get:

```
{
  "id": "d03a227b-9786-428c-b635-4b5fbb8887dd",
  "type": "BadRequestError",
  "message": "request/body must NOT have additional properties",
  "description": "/body/prop1",
  "stack": "Bad Request: request/body must NOT have additional properties\n    at Object.POST-/v1/test-application/json (/node_modules/express-openapi-validator/dist/middlewares/openapi.request.validator.js:134:31)\n    at RequestValidator.validate (/node_modules/express-openapi-validator/dist/middlewares/openapi.request.validator.js:48:41)\n    at /node_modules/express-openapi-validator/dist/openapi.validator.js:233:53\n    at /node_modules/express-openapi-validator/dist/openapi.validator.js:165:28\n    at process.processTicksAndRejections (node:internal/process/task_queues:103:5)"
}
```
and if I send `{
  "prop2": "string",
  "prop5": "string"
}` (excluding the "additional" property)

I get:

```
{
  "id": "e2220989-16b0-4812-9540-f6d6e3931e32",
  "type": "BadRequestError",
  "message": "request/body must have required property 'prop1', request/body must have required property 'prop4', request/body must match exactly one schema in oneOf",
  "description": "/body/prop1",
  "stack": "Bad Request: request/body must have required property 'prop1', request/body must have required property 'prop4', request/body must match exactly one schema in oneOf\n    at Object.POST-/v1/test-application/json (/node_modules/express-openapi-validator/dist/middlewares/openapi.request.validator.js:134:31)\n    at RequestValidator.validate (/node_modules/express-openapi-validator/dist/middlewares/openapi.request.validator.js:48:41)\n    at /node_modules/express-openapi-validator/dist/openapi.validator.js:233:53\n    at /node_modules/express-openapi-validator/dist/openapi.validator.js:165:28\n    at process.processTicksAndRejections (node:internal/process/task_queues:103:5)"
}
```

In this scenario, validation around `additionalProperties: false` is broken and unusable. Is there a configuration to achieve the goal here?
