### ISSUE TITLE
Add support for user-defined keywords 

### ISSUE THREAD

**Issue by constanzaderienzo** [cdimascio/express-openapi-validator#927]
**Is your feature request related to a problem? Please describe.**
Given our business logic, we are in need of adding custom-keywords.

For example:
```
in: path
name: offset
schema:
    type: number
    coerceEmtpyValue: true # Custom keyword
```

We found that AJV has this feature: https://ajv.js.org/guide/user-keywords.html#user-defined-keywords.

However, there is no way to extend the Ajv instance used by the validator (or at least we couldn't find one).

**Describe the solution you'd like**
Support for custom-keywords.
